---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 257171
custom_fields:
- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
  description: Countdown to your custom holidays. Support absolute dates, date of month, and <b class="font-normal italic">n</b>-th weekday of month.
  github_url: https://github.com/blueset/trmnl-recipes
  category: calendar,personal
- keyname: holidays
  field_type: code
  name: Holidays
  description: |
    Define your custom holidays here. You can use absolute dates, date of month, or <b class="font-normal italic">n</b>-th weekday of month formats.<br>
    Use the <a href="https://blueset.github.io/trmnl-recipes/holiday-editor/index.html" target="_blank" class="underline">Holiday Editor</a> to easily add, edit, and manage your holidays, or learn more about the <a href="https://blueset.github.io/trmnl-recipes/holiday-editor/index.html#reference" target="_blank" class="underline">supported date formats</a>.
  placeholder: |
    - name: Christmas Day (Date of month)
      date: 12-25  # Format: MM-DD
      icon: fluent-ioji-flat:fireworks  # Icon for the holiday, find yours at https://icon-sets.iconify.design/
      round: [1, 2, 3, 4, 5]  # Optional: Round to nearest weekday (1=Monday, 7=Sunday)
    - name: Year 2038 problem (Absolute date)
      date: 2038-01-19  # Format: YYYY-MM-DD
      icon: mdi:cpu-32-bit
    - name: US Memorial Day (last n-th weekday of month)
      date: 05Wn1-1  # Format: MWnw-D (e.g., 05Wn1-1 for last Monday of May)
      icon: fluent-ioji-flat:reindeer-ribbon
    - name: Chinese New Year (Date of month with different calendar)
      date: 01-01[u-ca=chinese]  # Format: MM-DD[u-ca=calendar] (e.g., 01-01[u-ca=chinese] for Chinese New Year)
      icon: fluent-ioji-flat:red-envelope
  default: |-
    - name: Christmas Day (Date of month)
      date: 12-25  # Format: MM-DD
      icon: fluent-ioji-flat:fireworks  # Icon for the holiday, find yours at https://icon-sets.iconify.design/
      round: [1, 2, 3, 4, 5]  # Optional: Round to nearest weekday (1=Monday, 7=Sunday)
    - name: Year 2038 problem (Absolute date)
      date: 2038-01-19  # Format: YYYY-MM-DD
      icon: mdi:cpu-32-bit
    - name: US Memorial Day (last n-th weekday of month)
      date: 05Wn1-1  # Format: MWnw-D (e.g., 05Wn1-1 for last Monday of May)
      icon: fluent-ioji-flat:reindeer-ribbon
    - name: Chinese New Year (Date of month with different calendar)
      date: 01-01[u-ca=chinese]  # Format: MM-DD[u-ca=calendar] (e.g., 01-01[u-ca=chinese] for Chinese New Year)
      icon: fluent-ioji-flat:red-envelope
name: Custom Next Holiday
refresh_interval: 1440
