---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.1.1
serverless_language: node
polling_url: ''
polling_headers: ''
polling_body: ''
id: 344030
custom_fields:
- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
- keyname: vendors
  field_type: select
  name: Vendors
  help_text: Use <kbd>⌘</kbd>+<kbd>click</kbd> or <kbd>ctrl</kbd>+<kbd>click</kbd> to select and deselect multiple options.
  options:
  - Building 3 Espresso: b3espresso
  - Building 7 Espresso: b7espresso
  - Building 92 Espresso: cafe92
  - Café 109: cafe109
  - Café 121: cafe121
  - Café 16: cafe16
  - Café 25: cafe25
  - Café 31: cafe31
  - Café 34 – in.gredients: in-gredients
  - Café 34: cafe34
  - Café 36: cafe36
  - Café 37: cafe37
  - Café 40/41: cafe40-41
  - Café 43: cafe43
  - Café 50: cafe50
  - Café 83: cafe83
  - Café 86: cafe86
  - Café 99: cafe99
  - Café Millennium E: cafemille
  - Café RedWest: caferedwest
  - Café RTC: cafertc5
  - Café Studio H: cafestudioh
  - Commons – Boardwalk: boardwalk
  - Commons – Bowlna: bowlna
  - Commons – Chandy's: chandys
  - Commons – Himalaya: himalaya
  - Commons – Hometown: hometown
  - Commons – Just Poké: justpoke
  - Commons – Maya's Mexican + Pita: mayas
  - Commons – S'wich: s-wich
  - Commons – Typhoon!: typhoon
  - Food Hall 4: foodhall4
  - Food Hall 4 – Boon Boona: fh4boonboona
  - Food Hall 4 – Jack's BBQ: fh4jacksbbq
  - Food Hall 4 – Joe's Burgers: fh4joesburger
  - Food Hall 4 – Just Poke: fh4justpoke
  - Food Hall 4 – MiLa: fh4mila
  - Food Hall 4 – Paparepas: fh4papparepas
  - Food Hall 6: foodhall6
  - Food Hall 6 – Bobae: bobae
  - Food Hall 6 – Craft75 Pub: craft75
  - Food Hall 6 – Dote: dote
  - Food Hall 6 – L'Experience: l-experience
  - Food Hall 6 – Pinkabella Cupcakes: pinkabella
  - Food Hall 9: foodhall9
  - Food Hall 9 – Big Chicken: fh9bigchicken
  - One Esterra Food Hall: one-esterra
  - Redmond Transit Station – Dote: dote-rts
  - Studio A Espresso: studioa
  - Studio D Espresso: studiod
  multiple: true
name: Menu
refresh_interval: 15
