---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.1.1
serverless_language: ''
polling_url: ''
polling_headers: ''
polling_body: ''
id: 187661
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: doesnt_matter
  name: About This Plugin
  field_type: author_bio
  description: Word clock in Japanese. Supports 24-hour and 12-hour formats, with a maximum display precision of 5 minutes (depending on recipe and device update frequency).
  description-ja: 日本語の文字時計。24 時制と 12 時制対応、最大表示精度は 5 分（レシピとデバイスの更新頻度による）。
  github_url: https://github.com/blueset/trmnl-recipes
  category: productivity,calendar
- keyname: cycle
  field_type: select
  name: Time format
  name-ja: 時刻表示方法
  default: h23
  options:
  - 24-hour: h23
  - 12-hour: h12
  options-ja:
  - 24 時制: h23
  - 12 時制: h12
name: Word Clock 日本語
refresh_interval: 15
